config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :tasks
  resources :services, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  TYPES = ['electrician', 'plumber', 'gardener', 'housekeeper', 'cook'].freeze

  has_many :tasks

  validates :name, :classification, presence: true
  validates :classification, inclusion: { in: Service::TYPES }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  respond_to :js

  def index
    @services = Service.where(classification: params["classification"])
    @type = params["classification"]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:update, :edit, :destroy]
  respond_to :html, :js

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)
  end

  def edit
    @service_type = @task.service.classification
    @services = Service.where(classification: @task.service.classification)
  end

  def update
    @task.update(task_params)
  end

  def destroy
    @task.destroy
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :service_id, :longtitude, :latitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def active_service(service_id, current_id)
    'active-service' if service_id == current_id
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def active_class(service_type, current_type)
    'active-type-service' if service_type == current_type
  end

  def task_full_title(task)
    if task.service
      "I need a #{task.service.classification} to #{task.service.name}, #{task.title}"
    else
      task.title
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JobUp</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li class="<%= "active-link" if current_page?(root_path) %>">
          <%= link_to('Dashboard', root_path) %>
        </li>
        <li>
          <a href="#">History</a>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            </li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tgm</title>
    <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyA6jjTiFMlGP3gGTUF0XP0l4917iDCyYNk"></script>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container" id="map-container"></div>
    <div id="over_map">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/services/_services.html.erb
<% if @services.exists? %>
  <p class="new-task-modal__subtitle"><%= @services.first.classification %> tasks</p>
  <% @services.each do |service| %>
    <div>
      <p class="service-name <%= active_service(id, service.id) %>" data-service-id="<%= service.id %>" data-service-name="<%= service.name %>" data-service-type="<%= service.classification %>"><%= service.name %></p>
    </div>
  <% end %>
<% else %>
  <p>There are no services</p>
<% end %>

app/views/services/_type.html.erb
<div class="task__service-type" id="<%= type %>">
  <%= link_to services_path(classification: type), remote: true do %>
    <div class="<%= active_class(@service_type, type) %>">
      <%= image_tag("#{type}.svg") %>
    </div>
    <p class="task__service-type-name"><%= type.camelize %></p>
  <% end %>
</div>

app/views/services/index.js.erb
$('.task__service-type div').removeClass('active-type-service');
$('#' + "<%= @type %>" + ' div').addClass('active-type-service');
$('#task-services').html("<%= j (render(partial: 'services', locals: { id: '' })) %>");

app/views/tasks/_form.html.erb
<div id="new-task">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for @task, remote: true do |f|   %>
        <%= f.hidden_field :service_id, value: @task.service.try(:id) %>
        <%= f.hidden_field :longtitude, value: @task.longtitude %>
        <%= f.hidden_field :latitude, value: @task.latitude %>

        <div class="modal-header">
          <p class="modal-title new-task-modal__subtitle">New task</p>
          <div id="modal-task-title"><%= task_full_title(@task) %></div>
          <div id="modal-task-address"></div>
          <%= f.submit btn_value, class: 'btn btn-primary' %>
        </div>
        <div class="modal-body">
          <div class="task__form-info">
            <p class="new-task-modal__subtitle">location</p>
            <p class="new-task-modal__address"></p>
          </div>

          <div class="task__form-info">
            <p class="new-task-modal__subtitle">service type</p>
            <% Service::TYPES.each do |type| %>
              <%= render partial: 'services/type', locals: { type: type} %>
            <% end %>
          </div>

          <div class="task__form-info" id='task-services'>
          </div>

          <div class="task__form-info">
            <p class="new-task-modal__subtitle">task description</p>
            <div class="task-description"></div>
            <%= f.text_area :title, value: @task.title, id: 'task-input-description' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="task-wrapper" id="task-<%= task.id %>">
  <p class="task-held-at-time">
    <%= task.created_at.to_formatted_s(:long) %>
  </p>
  <p class="task-title">
    I need a <%= task.service.classification %> to <%= task.service.name %>
  </p>
  <p class="task-service hidden" data-service-name="<%= task.service.name %>" data-service-classification="<%= task.service.classification %>"></p>
  <p class="task-run-btns">
    <%= link_to "EDIT", edit_task_path(task), class: "btn btn-primary", remote: true %>
    <%= link_to 'DELETE', task_path(task), class: "btn btn-primary", method: 'delete', remote: true, data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/tasks/create.js.erb
<% if @task.valid? %>
  $('#task-form').animate({ "right": "0" }, "slow" )
  $('#wrapper').append('<%= j render @task %>')
<% else %>
  $('.modal-header').append('Please, choose service type')
<% end %>

app/views/tasks/destroy.js.erb
$('#task-form').animate({ "right": "0" }, "slow" )
$("#task-<%= @task.id %>").remove()

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j render(partial: 'form', locals: { btn_value: 'UPDATE TASK' }) %>");
$('#task-services').html("<%= j render(partial: 'services/services', locals: { id: @task.service.id }) %>");
$('#task-form').animate({ "right": "470px" }, "slow" );

var taskLatlng;

taskLatlng = {
  lat: parseFloat("<%= @task.latitude %>"),
  lng: parseFloat("<%= @task.longtitude %>")
};

reDrawMarkers(taskLatlng)

app/views/tasks/index.html.erb
<div id="wrapper">
  <div class="task-wrapper">
    <%= link_to "New task", new_task_path, remote: true, class: 'btn btn-demo new-task-btn' %>
  </div>

  <% @tasks.each do |task| %>
    <%= render partial: "task", locals: {task: task} %>
  <% end %>

  <div id="task-form"></div>
</div>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j render(partial: 'form', locals: { btn_value: 'CREATE TASK' }) %>");
$('#task-form').animate({ "right": "470px" }, "slow" )
var dniproMenoraLat = 48.463819;
var dniproMenoraLng = 35.053189;
var taskLatlng;

taskLatlng = {
  lat: dniproMenoraLat,
  lng: dniproMenoraLng
};

reDrawMarkers(taskLatlng);

app/views/tasks/update.js.erb
$('#task-form').animate({ "right": "0" }, "slow" )
$('#wrapper #task-' + "<%= @task.id %>").replaceWith('<%= j render @task %>')